`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: Yale University
// Engineer: William Kalfus
// 
// Create Date: 11/10/2022 03:24:36 PM
// Design Name: acadia
// Module Name: acadia_tb
// Project Name: acadia
// Target Devices: ZCU216
// Tool Versions: 2020.2
// Description: A testbench intended to verify the functionality of the complete
//              block design, including exposing internal signals to verify 
//              internal signal processing, latencies, and timing relationships.
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module acadia_tb();
    
    // -------------------------- Declare many signals that will be useful for debugging ----------------------------
    
    // DAC clock generated by external source (in this case, manually in the testbench)
    reg          clk_p;   
   
    // Sequencer resetn and run signals
    reg  [90:0]  debug_gpio;
    
    // Clock wizard outputs
    wire         clk_wiz_locked;
    wire         clk_wiz_seq_clk;

    // Internal simulation signals
    reg          resp;
    
    reg [511:0]  cache_data;
    
    // -------------------------- Assign the signals to their companions in the block design using hierarchical references ----------------------------

    // Connect some of our test signals to internal pins in the block design

    
//    // Clock wizard outputs
    assign clk_wiz_locked  = acadia_tb.uut.hedgehog.clk_wiz.locked;
    assign clk_wiz_seq_clk = acadia_tb.uut.hedgehog.clk_wiz.seq_clk;  

    // -------------------------- Drive the DAC clock ----------------------------
    initial begin       
        clk_p = 1'b0;
    end
    
    always begin
        #2 clk_p = ~clk_p;
    end

    // -------------------------- Instantiate the block design ----------------------------
    acadia_bd uut
       (.DDR4_C0_SYS_CLK_clk_n(),
        .DDR4_C0_SYS_CLK_clk_p(),
        .CLK104_PL_CLK_clk_n(~clk_p),
        .CLK104_PL_CLK_clk_p(clk_p),
        .DDR4_C0_act_n(),
        .DDR4_C0_adr(),
        .DDR4_C0_ba(),
        .DDR4_C0_bg(),
        .DDR4_C0_ck_c(),
        .DDR4_C0_ck_t(),
        .DDR4_C0_cke(),
        .DDR4_C0_cs_n(),
        .DDR4_C0_dm_n(),
        .DDR4_C0_dq(),
        .DDR4_C0_dqs_c(),
        .DDR4_C0_dqs_t(),
        .DDR4_C0_odt(),
        .DDR4_C0_reset_n(),
        .DDR4_C1_SYS_CLK_clk_n(),
        .DDR4_C1_SYS_CLK_clk_p(),
        .DDR4_C1_act_n(),
        .DDR4_C1_adr(),
        .DDR4_C1_ba(),
        .DDR4_C1_bg(),
        .DDR4_C1_ck_c(),
        .DDR4_C1_ck_t(),
        .DDR4_C1_cke(),
        .DDR4_C1_cs_n(),
        .DDR4_C1_dm_n(),
        .DDR4_C1_dq(),
        .DDR4_C1_dqs_c(),
        .DDR4_C1_dqs_t(),
        .DDR4_C1_odt(),
        .DDR4_C1_reset_n(),
        .debug_gpio(debug_gpio)
        
        );
    
    // -------------------------- Simulate the PS writing commands to run the testbench ----------------------------
    initial begin
        debug_gpio = 91'd0;
        
        // Reset everything
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b1);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b0);
        acadia_tb.uut.ps.inst.fpga_soft_reset(4'h1);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b1);
        acadia_tb.uut.ps.inst.fpga_soft_reset(4'h0);
        
        // Wait for the clocks to lock
        @(posedge clk_wiz_locked);
        
        repeat(30) @(posedge clk_p);
        
        
        // Add AXI data loading here!
        

        repeat(30) @(posedge clk_p);
        
        debug_gpio = {2'b11, 89'd0};
        
        repeat(3000) @(posedge clk_p);
        
        debug_gpio = {2'b00, 89'd0};
        
        
        $finish;
    end


endmodule
