`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: Yale University
// Engineer: William Kalfus
// 
// Create Date: 11/10/2022 03:24:36 PM
// Design Name: acadia
// Module Name: acadia_tb
// Project Name: acadia
// Target Devices: ZCU216
// Tool Versions: 2020.2
// Description: A testbench intended to verify the functionality of the complete
//              block design, including exposing internal signals to verify 
//              internal signal processing, latencies, and timing relationships.
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module acadia_tb();
    
    
    // clock generated by external source (in this case, manually in the testbench)
    wire          clk_p;   
   
    // Internal simulation signals
    reg          resp;
    
    reg [31:0] data;
    
    assign clk_p = acadia_tb.uut.ps_pl_clk0;
    
    // -------------------------- Assign the signals to their companions in the block design using hierarchical references ----------------------------

    // Connect some of our test signals to internal pins in the block design

    
//    // Clock wizard outputs

    // -------------------------- Drive the DAC clock ----------------------------
//    initial begin       
//        clk_p = 1'b0;
//    end
    
//    always begin
//        #2.5 clk_p = ~clk_p;
//    end

    // -------------------------- Instantiate the block design ----------------------------
    acadia_bd uut
       (.ADCIO(),
        .CLK104_PL_CLK_clk_n(~clk_p),
        .CLK104_PL_CLK_clk_p(clk_p),
        .CLK104_PL_SYSREF_clk_n(),
        .CLK104_PL_SYSREF_clk_p(),
        .CLK104_SFP_REC_CLK_clk_n(),
        .CLK104_SFP_REC_CLK_clk_p(),
        .CLK104_SPI_sel(),
        .CLK104_sync(),
        .DACIO(),
        .FMCP_CLK1_M2C_clk_n(),
        .FMCP_CLK1_M2C_clk_p(),
        .IDT_8A34001_CLK5_clk_n(),
        .IDT_8A34001_CLK5_clk_p(),
        .IDT_8A34001_GPIO(),
        .IDT_8A34001_Q11_clk_n(),
        .IDT_8A34001_Q11_clk_p(),
        .IDT_8A34001_Q1_clk_n(),
        .IDT_8A34001_Q1_clk_p(),
        .IDT_8A34001_Q2_clk_n(),
        .IDT_8A34001_Q2_clk_p(),
        .IDT_8A34001_Q3_clk_n(),
        .IDT_8A34001_Q3_clk_p(),
        .IDT_8A34001_Q8_clk_n(),
        .IDT_8A34001_Q8_clk_p(),
        .MGT128_C0_grx_n(),
        .MGT128_C0_grx_p(),
        .MGT128_C0_gtx_n(),
        .MGT128_C0_gtx_p(),
        .PMOD0(),
        .PMOD1()
        );
    
    // -------------------------- Simulate the PS writing commands to run the testbench ----------------------------
    initial begin
        
        // Reset everything
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b1);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b0);
        acadia_tb.uut.ps.inst.fpga_soft_reset(4'h1);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b1);
        acadia_tb.uut.ps.inst.fpga_soft_reset(4'h0);

        
        repeat(1000) @(posedge clk_p);
        
        
        // Add AXI data loading here!
        acadia_tb.uut.ps.inst.write_data(32'h80000800, 4, 32'hD0ADB00B, resp);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.write_data(32'h80000808, 4, 32'h12345678, resp);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.write_data(32'h8000080C, 4, 32'hABCD6543, resp);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.read_data(32'h80000804, 4, data, resp);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.write_data(32'h80000808, 4, 32'h0ABC89AB, resp);
        repeat(30) @(posedge clk_p);
        acadia_tb.uut.ps.inst.read_data(32'h80000800, 4, data, resp);
        repeat(30) @(posedge clk_p);
                
        
        $finish;
    end


endmodule
