DEFAULT_CONFIG = {
    # The primary clock rate of the logic
    "clk104_pl_clk": {
        "freq_hz": 250_000_000
    },

    # the externally-programmed frequency generated by the 8a34001
    "clk_8A34001_Q3_out": {
        "freq_hz": 250_000_000
    },
    
    # Configuration for the input to the clocking wizard
    "clocks": {
        "input_freq_hz": 250_000_000,
        "input_jitter_ps": 40.0,
        "input_source_type": "Global_buffer",

        "generated_clocks": {
            "seq_clk": 250_000_000,
            "dac_clk": 250_000_000,
            "adc_clk": 250_000_000,
            "hs_clk": 333_333_333,
        },
    },    

    # Memory segments physically located in the PS
    "memory": {
        "HPC0_LPS_OCM": {
            "address": 0x00_FF00_0000, 
            "size_bits": 8 * 2**18, 
            "segment": "/ps/SAXIGP0/HPC0_LPS_OCM"
        },

        "HPC1_LPS_OCM": {
            "address": 0x01_FF00_0000, 
            "size_bits": 8 * 2**18, 
            "segment": "/ps/SAXIGP1/HPC1_LPS_OCM"
        },

        "HP0_LPS_OCM": {
            "address": 0x02_FF00_0000, 
            "size_bits": 8 * 2 * 2**18, 
            "segment": "/ps/SAXIGP2/HP0_LPS_OCM"
        },

        "HP1_LPS_OCM": {
            "address": 0x03_FF00_0000, 
            "size_bits": 8 * 2**18, 
            "segment": "/ps/SAXIGP3/HP1_LPS_OCM"
        },

        "HPC0_DDR_LOW": {
            "address": 0x04_0000_0000, 
            "size_bits": 8 * 2**31, 
            "segment": "/ps/SAXIGP0/HPC0_DDR_LOW"
        },

        "HPC1_DDR_LOW": {
            "address": 0x05_0000_0000, 
            "size_bits": 8 * 2**31, 
            "segment": "/ps/SAXIGP1/HPC1_DDR_LOW"
        },

        "HP0_DDR_LOW": {
            "address": 0x06_0000_0000, 
            "size_bits": 8 * 2**31, 
            "segment": "/ps/SAXIGP2/HP0_DDR_LOW"
        },

        "HP1_DDR_LOW": {
            "address": 0x07_0000_0000, 
            "size_bits": 8 * 2**31, 
            "segment": "/ps/SAXIGP3/HP1_DDR_LOW"
        },

        "HPC0_DDR_HIGH": {
            "address": 0x08_0000_0000, 
            "size_bits": 8 * 2**35, 
            "segment": "/ps/SAXIGP0/HPC0_DDR_HIGH"
        },

        "HPC1_DDR_HIGH": {
            "address": 0x18_0000_0000, 
            "size_bits": 8 * 2**35, 
            "segment": "/ps/SAXIGP1/HPC1_DDR_HIGH"
        },

        "HP0_DDR_HIGH": {
            "address": 0x28_0000_0000, 
            "size_bits": 8 * 2**35, 
            "segment": "/ps/SAXIGP2/HP0_DDR_HIGH"
        },

        "HP1_DDR_HIGH": {
            "address": 0x38_0000_0000, 
            "size_bits": 8 * 2**35, 
            "segment": "/ps/SAXIGP3/HP1_DDR_HIGH"
        },

        "ddr4_c0": {
            "address": 0x40_0000_0000, 
            "size_bits": 8 * 2**32, 
            "segment": "DDR4_C0_MIG/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK"
        },

        "ddr4_c1": {
            "address": 0x41_0000_0000, 
            "size_bits": 8 * 2**32, 
            "segment": "DDR4_C1_MIG/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK"
        },
    },

    # The clock rate for the sequencer memory crossbar
    "sequencer_memory_crossbar": {
        "clock": "hs_clk"
    },

    # The clocks used to drive the PS AXI interfaces
    "ps_axi_clocks": {
        "PS_MAXIHPM0_FPD": "hs_clk",
        "PS_MAXIHPM1_FPD": "hs_clk",
        "PS_MAXIHPM0_LPD": "hs_clk",
        "PS_SAXIHPC0_FPD": "hs_clk",
        "PS_SAXIHP0_FPD": "hs_clk",
        "PS_SAXIHPC1_FPD": "hs_clk",
        "PS_SAXIHP1_FPD": "hs_clk"
    },

    "sequencer_cache_memory": {
        "primitive": "block",
        "address": 0x00_b000_0000, 
        "segment": "s_axi/reg0",
        "size_bits": 2**20,
        "bus_pipeline": False,
        "synchronous": False,
        "controller_width": 128,
        "controller_port_input_pipeline": 0,
        "controller_port_output_pipeline": 1,
        "bus_port_input_pipeline": 0,
        "bus_port_output_pipeline": 1
    },

    "sequencer_instruction_memory": {
        "primitive": "block",
        "address": 0x00_b100_0000, 
        "segment": "s_axi/reg0",
        "size_bits": 128*4096,
        "synchronous": False,
        "controller_width": 128,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "sequencer_port_input_pipeline": 0,
        "sequencer_port_output_pipeline": 0
    },

    "dac_tile0_sample_memory": {
        "primitive": "ultra",
        "interface_width": 128,
        "controller_width": 128,
        "address": 0x10_0000_0000,
        "size_bits": 2**20,
        "segment": "s_axi/reg0",
        "synchronous": True,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "dac_port_input_pipeline": 1,
        "dac_port_output_pipeline": 2
    },

    "dac_tile1_sample_memory": {
        "primitive": "ultra",
        "interface_width": 128,
        "controller_width": 128,
        "address": 0x10_0008_0000,
        "size_bits": 2**20,
        "segment": "s_axi/reg0",
        "synchronous": True,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "dac_port_input_pipeline": 1,
        "dac_port_output_pipeline": 2
    },

    "dac_tile2_sample_memory": {
        "primitive": "ultra",
        "interface_width": 128,
        "controller_width": 128,
        "address": 0x10_0010_0000,
        "size_bits": 2**20,
        "segment": "s_axi/reg0",
        "synchronous": True,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "dac_port_input_pipeline": 1,
        "dac_port_output_pipeline": 2
    },

    "dac_tile3_sample_memory": {
        "primitive": "ultra",
        "interface_width": 128,
        "controller_width": 128,
        "address": 0x10_0018_0000,
        "size_bits": 2**20,
        "segment": "s_axi/reg0",
        "synchronous": True,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "dac_port_input_pipeline": 1,
        "dac_port_output_pipeline": 2
    },

    "dac_dma_descriptor_memory": {
        "primitive": "block",
        "address": 0x10_0020_0000, 
        "size_bits": 1024*64,
        "segment": "s_axi/reg0",
        "synchronous": True,
        "controller_width": 32,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "dma_port_input_pipeline": 1,
        "dma_port_output_pipeline": 2
    },
        
    "adc_dma_descriptor_memory": {
        "primitive": "block",
        "address": 0x10_0030_0000, 
        "size_bits": 1024*64,
        "segment": "s_axi/reg0",
        "synchronous": True,
        "controller_width": 32,
        "controller_port_input_pipeline": 2,
        "controller_port_output_pipeline": 2,
        "dma_port_input_pipeline": 1,
        "dma_port_output_pipeline": 2
    },
    
    "stream_processing_path": {
        # The maximum allowed width of inputs to be connected to the stream
        # processing path.
        "width": 128,
        "clock": "seq_clk",
            
        # The inputs to the stream processing path. There may be a total of 16 
        # inputs (limited by the number of available inputs on Xilinx's AXIS 
        # switch).
        # 
        # Available inputs are:
        # "ADC": The DMA output of the specified ADC. 
        #     All ADCs not specified here will be connected to a switch, whose
        #     outputs may be specified as capture stream inputs using the 
        #     "ADC_SWITCHx" specifier. 
        # "ADC_switch": An output of the ADC switch. The number of specifiers
        #     included here determines the number of outputs present on the
        #     switch, and if none are specified the switch is omitted and all
        #     ADCs not specified in this list are disconnected
        # "bulk": A MM2S DataMover is added to the bulk memory SmartConnect. 
        #     Note that the total number of processing modules, bulk inputs, and adders
        #     is 15 (limited by the available number of slave ports on the bulk
        #     AXI SmartConnect, with one port reserved for the PS).
        # "config": A MM2S DataMover is added to the config SmartConnect. 
        # "sequencer": A MM2S DataMover is added to the sequencer crossbar
        "inputs": [
            {"kind": "ADC", 
             "channel": 0,
             "datamover_controller_bus_pipeline": True},
            {"kind": "ADC", 
             "channel": 2,
             "datamover_controller_bus_pipeline": True},
            {"kind": "ADC", 
             "channel": 4,
             "datamover_controller_bus_pipeline": True},
            {"kind": "ADC", 
             "channel": 6,
             "datamover_controller_bus_pipeline": True},
            {"kind": "ADC_switch", 
             "datamover_controller_bus_pipeline": True},
            {"kind": "ADC_switch", 
             "datamover_controller_bus_pipeline": True},
            {"kind": "memory",
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "datamover_controller_bus_pipeline": True},
            {"kind": "memory",
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "datamover_controller_bus_pipeline": True},
        ],
        
        # All of the inputs to the stream processing path pass through an AXIS
        # switch. Some of the inputs to this switch will be driven directly by 
        # an ADC output, but there are too many ADCs to directly connect all of
        # them (and it's unlikely that they'll all be needed at the same time 
        # anyway). Therefore, there is an additional switch that multiplexes 
        # all of the ADCs that are not directly connected to the stream 
        # processing path input switch. It provides a small number of outputs, 
        # which are then connected to the stream processing path input switch. 
        "input_switch": {
            "axi_address": 0x10_0040_0000, 
            "axi_size_bits": 8 * 2**18,
            "axi_segment": "S_AXI_CTRL/Reg",
            "axi_clk": "seq_clk"
        },
        
        "adc_input_switch": {
            "axi_address": 0x10_0050_0000, 
            "axi_size_bits": 8 * 2**18,
            "axi_segment": "S_AXI_CTRL/Reg",
            "axi_clk": "seq_clk"
        },
        
        # The stream processing modules present in the stream processing path.
        # All of the inputs specified above are connected to a switch, and the 
        # outputs of the switch are connected to the stream inputs of these 
        # modules. All of the modules have their own DataMover at the output 
        # for writing the results to a location on an AXI network. 
        # 
        # Note that the total number of modules is 15 (this is limited by 
        # the available number of slave ports on any SmartConnect, with one
        # slave port reserved for the PS). 
        "modules": [
            {"kind": "memory",
             "AXI_width": 256,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": True,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True}, 
            {"kind": "memory",
             "AXI_width": 256,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": True,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True}, 
            {"kind": "cmacc",
             "AXI_width": 32,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": False,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True,
             "kernel_memory_depth": 2048},
            {"kind": "cmacc",
             "AXI_width": 32,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": False,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True,
             "kernel_memory_depth": 2048},
            {"kind": "dsp",
             "AXI_width": 64,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": True,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True},
            {"kind": "dsp",
             "AXI_width": 64,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": True,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True},
            {"kind": "dsp",
             "AXI_width": 64,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "registers_bus_pipeline": True,
             "datamover_burst_size": 128,
             "datamover_controller_bus_pipeline": True},
            {"kind": "dsp",
             "AXI_width": 64,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "datamover_burst_size": 128,
             "registers_bus_pipeline": True,
             "datamover_controller_bus_pipeline": True},
            {"kind": "adder",
             "AXI_width": 256,
             "AXI_clock": "hs_clk",
             "FIFO_depth": 512,
             "FIFO_primitive": "auto",
             "output_word_width": 32,
             "datamover_burst_size": 128,
             "registers_bus_pipeline": True,
             "datamover_controller_bus_pipeline": True}, 
        ],
        
        # Some shared settings for any CMACCs used
        # If there are no CMACCs, these are ignored
        "cmacc_kernel_memory_controller": {
            "base_address": 0x10_0060_0000, 
            "segment": "s_axi/reg0",
            "controller_width": 32,
            "controller_port_input_pipeline": 2,
            "controller_port_output_pipeline": 2,
        }
    },

    "rfdc": {
        # is the axi config port of the rfdc synchronous to the sequencer?
        "axi_synchronous": True,

        # if axi_synchronous is true then this must be the sequencer clock frequency
        "axi_clk_freq_hz": 250e6,
        
        "axi_address": 0x10_0070_0000, 
        "axi_size_bits": 8 * 2**18,
        "axi_segment": "s_axi/reg",

        "dac": {
            "channel_interface_width": [128]*16,
            "channel_pipeline_stages": [1]*16,
            "channel_nyquist_zone": [1]*16,
            "tile_axis_clocks": ["dac_clk", "dac_clk", "dac_clk", "dac_clk"],
            "tile_mts": [True]*4,
            "tile_sample_rate_hz": [6e9]*4,
            "tile_pll": [True]*4,
            "tile_clk_source": [6]*4,
            "tile_refclk_freq_hz": [250e6]*4,
            "tile_distribute_clk": [0, 0, 1, 0],
            "tile_vop": [20.0]*4,
        },

        "adc": {
            "channel_interface_width": [128]*16,
            "channel_pipeline_stages": [1]*16,
            "channel_dither": [False]*16,
            "tile_axis_clocks": ["adc_clk", "adc_clk", "adc_clk", "adc_clk"],
            "tile_mts": [True]*4,
            "tile_sample_rate_hz": [2e9]*4,
            "tile_pll": [True]*4,
            "tile_clk_source": [2]*4,
            "tile_refclk_freq_hz": [250e6]*4,
            "tile_distribute_clk": [0, 0, 1, 0],
            "tile_dsa": [0]*4
        }    
    },

    "ps_gpio": {
        "sysfs_offset": 338 + 3*26,
        "sequencer_run": 90,
        "sequencer_nrst": 89, # The GPIO bit connected to the sequencer run synchronizer
        "clk104_sync": 88,
        "clk104_spi1": 87,
        "clk104_spi0": 86,
        "ddr4_c0_sys_rst": 85,
        "ddr4_c1_sys_rst": 84,
        "clk_wiz_locked": 82,
        "ddr4_c0_cal_cplt": 81,
        "ddr4_c1_cal_cplt": 80,
        "sequencer_bus3": 0,
        "sequencer_bus4": 32,
        "sequencer_bus5": 64
    },

    "sequencer_bus": {
        "decoder_pipeline_miso": True,

        "dma_pipeline": [True]*32,

        "io_dataport": {
            "bus_pipeline": True,
            "ADCIO_pipeline": 2,
            "DACIO_pipeline": 2
        },

        "dma_running_dataport": {
            "bus_pipeline": True,
            "pipeline": [1]*32,
        },

        "dma_trigger_dataport": {
            "bus_pipeline": False,
            "pipeline": [1]*32,
        },

        "rfdc_rts": {
            "bus_pipeline": True,
            "nco_clk": "seq_clk"
        },
        
        "ps_gpio3": {
            "width": 32,
            "pipeline": 2,
            "bus_pipeline": True
        },

        "ps_gpio4": {
            "width": 32,
            "pipeline": 2,
            "bus_pipeline": True
        },

        "ps_gpio5": {
            "width": 16,
            "pipeline": 2,
            "bus_pipeline": True
        },

        "ps_irq": {
            "irq_pipeline": 2,
            "gdma_pipeline": 2,
            "bus_pipeline": True
        },

        "zdma_controller": {
            "bus_pipeline": True
        },

        "clk104_sync_dataport": {
            "bus_pipeline": True,
            "pipeline": 2
        }
    }
}
