create_clock -period 3.333 -name clk104_pl_clk [get_ports CLK104_PL_CLK_clk_p]

# Set multicycle path constraints on internal signals to the RF data converter (from the example design)
set_multicycle_path -to [get_pins -filter {REF_PIN_NAME== D} -of [get_cells -hier -filter {name =~ acadia_bd_i/hedgehog/rfdc/inst/IP2Bus_Data_reg*}]] -setup 2
set_multicycle_path -to [get_pins -filter {REF_PIN_NAME== D} -of [get_cells -hier -filter {name =~ acadia_bd_i/hedgehog/rfdc/inst/IP2Bus_Data_reg*}]] -hold 1

# Add a max delay constraint between the clock generated by the PS and those generated by the RF tile
set_max_delay 3.3333 -from [get_clocks -include_generated_clocks clk_pl_0] -to [get_clocks -include_generated_clocks [get_clocks -filter {name =~ RF*_CLK}]] -datapath_only
set_max_delay 3.3333 -from [get_clocks -include_generated_clocks [get_clocks -filter {name =~ RF*_CLK}]] -to [get_clocks -include_generated_clocks clk_pl_0] -datapath_only

# CLK104 connections
set_property PACKAGE_PIN D11       [get_ports "CLK104_PL_SYSREF_N"] ;   # Bank  89 VCCO - VCC1V8   - IO_L8N_HDGC_AD4N_89
set_property IOSTANDARD  LVDS_25   [get_ports "CLK104_PL_SYSREF_N"] ;   # Bank  89 VCCO - VCC1V8   - IO_L8N_HDGC_AD4N_89
set_property PACKAGE_PIN E11       [get_ports "CLK104_PL_SYSREF_P"] ;   # Bank  89 VCCO - VCC1V8   - IO_L8P_HDGC_AD4P_89
set_property IOSTANDARD  LVDS_25   [get_ports "CLK104_PL_SYSREF_P"] ;   # Bank  89 VCCO - VCC1V8   - IO_L8P_HDGC_AD4P_89
set_property PACKAGE_PIN E9        [get_ports "CLK104_PL_CLK_clk_n"] ;      # Bank  89 VCCO - VCC1V8   - IO_L7N_HDGC_AD5N_89
set_property IOSTANDARD  LVDS_25   [get_ports "CLK104_PL_CLK_clk_n"] ;      # Bank  89 VCCO - VCC1V8   - IO_L7N_HDGC_AD5N_89
set_property PACKAGE_PIN E10       [get_ports "CLK104_PL_CLK_clk_p"] ;      # Bank  89 VCCO - VCC1V8   - IO_L7P_HDGC_AD5P_89
set_property IOSTANDARD  LVDS_25   [get_ports "CLK104_PL_CLK_clk_p"] ;      # Bank  89 VCCO - VCC1V8   - IO_L7P_HDGC_AD5P_89
set_property PACKAGE_PIN BA22      [get_ports "CLK104_SFP_REC_CLK_N"] ; # Bank  66 VCCO - VADJ_FMC - IO_L5N_T0U_N9_AD14N_66
set_property IOSTANDARD  LVDS      [get_ports "CLK104_SFP_REC_CLK_N"] ; # Bank  66 VCCO - VADJ_FMC - IO_L5N_T0U_N9_AD14N_66
set_property PACKAGE_PIN AY22      [get_ports "CLK104_SFP_REC_CLK_P"] ; # Bank  66 VCCO - VADJ_FMC - IO_L5P_T0U_N8_AD14P_66
set_property IOSTANDARD  LVDS      [get_ports "CLK104_SFP_REC_CLK_P"] ; # Bank  66 VCCO - VADJ_FMC - IO_L5P_T0U_N8_AD14P_66
# set_property PACKAGE_PIN L15       [get_ports "CLK104_SYNC_IN"] ;       # Bank  88 VCCO - VCC1V8   - IO_L5P_HDGC_88
# set_property IOSTANDARD  LVCMOS18  [get_ports "CLK104_SYNC_IN"] ;       # Bank  88 VCCO - VCC1V8   - IO_L5P_HDGC_88

# SI570
# set_property PACKAGE_PIN AR19            [get_ports "USER_SI570_C0_N"] ; # Bank  65 VCCO - VCC1V2   - IO_L12N_T1U_N11_GC_65
# set_property IOSTANDARD  DIFF_SSTL12_DCI [get_ports "USER_SI570_C0_N"] ; # Bank  65 VCCO - VCC1V2   - IO_L12N_T1U_N11_GC_65
# set_property PACKAGE_PIN AR20            [get_ports "USER_SI570_C0_P"] ; # Bank  65 VCCO - VCC1V2   - IO_L12P_T1U_N10_GC_65
# set_property IOSTANDARD  DIFF_SSTL12_DCI [get_ports "USER_SI570_C0_P"] ; # Bank  65 VCCO - VCC1V2   - IO_L12P_T1U_N10_GC_65

# 8A34001 connections
set_property PACKAGE_PIN Y40         [get_ports "CLK_8A34001_Q1_OUT_N"] ;  # Bank 128 - MGTYRXN3_128
set_property PACKAGE_PIN Y39         [get_ports "CLK_8A34001_Q1_OUT_P"] ;  # Bank 128 - MGTYRXP3_128
set_property PACKAGE_PIN AT24        [get_ports "CLK_8A34001_Q2_OUT_N"] ;    # Bank  66 VCCO - VADJ_FMC - IO_L11N_T1U_N9_GC_66
set_property IOSTANDARD  LVCMOS18    [get_ports "CLK_8A34001_Q2_OUT_N"] ;    # Bank  66 VCCO - VADJ_FMC - IO_L11N_T1U_N9_GC_66
set_property PACKAGE_PIN AT23        [get_ports "CLK_8A34001_Q2_OUT_P"] ;    # Bank  66 VCCO - VADJ_FMC - IO_L11P_T1U_N8_GC_66
set_property IOSTANDARD  LVCMOS18    [get_ports "CLK_8A34001_Q2_OUT_P"] ;    # Bank  66 VCCO - VADJ_FMC - IO_L11P_T1U_N8_GC_66
set_property PACKAGE_PIN G30         [get_ports "CLK_8A34001_Q3_OUT_N"] ;    # Bank  67 VCCO - VADJ_FMC - IO_L11N_T1U_N9_GC_67
set_property IOSTANDARD  LVCMOS18    [get_ports "CLK_8A34001_Q3_OUT_N"] ;    # Bank  67 VCCO - VADJ_FMC - IO_L11N_T1U_N9_GC_67
set_property PACKAGE_PIN H30         [get_ports "CLK_8A34001_Q3_OUT_P"] ;    # Bank  67 VCCO - VADJ_FMC - IO_L11P_T1U_N8_GC_67
set_property IOSTANDARD  LVCMOS18    [get_ports "CLK_8A34001_Q3_OUT_P"] ;    # Bank  67 VCCO - VADJ_FMC - IO_L11P_T1U_N8_GC_67
set_property PACKAGE_PIN T35         [get_ports "CLK_8A34001_Q7_OUT_N"] ;  # Bank 129 - MGTREFCLK1N_129
set_property PACKAGE_PIN T34         [get_ports "CLK_8A34001_Q7_OUT_P"] ;  # Bank 129 - MGTREFCLK1P_129
set_property PACKAGE_PIN H21         [get_ports "CLK_8A34001_Q8_OUT_N"] ;  # Bank  69 VCCO - VCC1V2   - IO_L11N_T1U_N9_GC_69
set_property IOSTANDARD  DIFF_SSTL12 [get_ports "CLK_8A34001_Q8_OUT_N"] ;  # Bank  69 VCCO - VCC1V2   - IO_L11N_T1U_N9_GC_69
set_property PACKAGE_PIN J21         [get_ports "CLK_8A34001_Q8_OUT_P"] ;  # Bank  69 VCCO - VCC1V2   - IO_L11P_T1U_N8_GC_69
set_property IOSTANDARD  DIFF_SSTL12 [get_ports "CLK_8A34001_Q8_OUT_P"] ;  # Bank  69 VCCO - VCC1V2   - IO_L11P_T1U_N8_GC_69
set_property PACKAGE_PIN Y35         [get_ports "CLK_8A34001_Q11_OUT_N"] ; # Bank 128 - MGTREFCLK1N_128
set_property PACKAGE_PIN Y34         [get_ports "CLK_8A34001_Q11_OUT_P"] ; # Bank 128 - MGTREFCLK1P_128

set_property PACKAGE_PIN R37       [get_ports "CLK_8A34001_CLK1_IN_N"] ; # Bank 128 - MGTYTXN3_128
set_property PACKAGE_PIN R36       [get_ports "CLK_8A34001_CLK1_IN_P"] ; # Bank 128 - MGTYTXP3_128
set_property PACKAGE_PIN AA37      [get_ports "CLK_8A34001_CLK5_IN_N"] ; # Bank 128 - MGTREFCLK0N_128
set_property PACKAGE_PIN AA36      [get_ports "CLK_8A34001_CLK5_IN_P"] ; # Bank 128 - MGTREFCLK0P_128
set_property PACKAGE_PIN V35       [get_ports "CLK_8A34001_CLK6_IN_N"] ; # Bank 129 - MGTREFCLK0N_129
set_property PACKAGE_PIN V34       [get_ports "CLK_8A34001_CLK6_IN_P"] ; # Bank 129 - MGTREFCLK0P_129

# 8A34001 GPIO
# We won't make these into a bus, because they may need different directions
# set_property PACKAGE_PIN H19         [get_ports "CLK_8A34001_GPIO_0"] ;# Bank  69 VCCO - VCC1V2   - IO_L9N_T1L_N5_AD12N_69
# set_property IOSTANDARD  LVCMOS12    [get_ports "CLK_8A34001_GPIO_0"] ;# Bank  69 VCCO - VCC1V2   - IO_L9N_T1L_N5_AD12N_69
# set_property PACKAGE_PIN J19         [get_ports "CLK_8A34001_GPIO_1"] ;# Bank  69 VCCO - VCC1V2   - IO_L9P_T1L_N4_AD12P_69
# set_property IOSTANDARD  LVCMOS12    [get_ports "CLK_8A34001_GPIO_1"] ;# Bank  69 VCCO - VCC1V2   - IO_L9P_T1L_N4_AD12P_69
# set_property PACKAGE_PIN K20        [get_ports "CLK_8A34001_GPIO_2"] ;# Bank  69 VCCO - VCC1V2   - IO_L7N_T1L_N1_QBC_AD13N_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_2"] ;# Bank  69 VCCO - VCC1V2   - IO_L7N_T1L_N1_QBC_AD13N_69
# set_property PACKAGE_PIN K21        [get_ports "CLK_8A34001_GPIO_3"] ;# Bank  69 VCCO - VCC1V2   - IO_L7P_T1L_N0_QBC_AD13P_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_3"] ;# Bank  69 VCCO - VCC1V2   - IO_L7P_T1L_N0_QBC_AD13P_69
# set_property PACKAGE_PIN L18        [get_ports "CLK_8A34001_GPIO_4"] ;# Bank  69 VCCO - VCC1V2   - IO_L6N_T0U_N11_AD6N_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_4"] ;# Bank  69 VCCO - VCC1V2   - IO_L6N_T0U_N11_AD6N_69
# set_property PACKAGE_PIN M18        [get_ports "CLK_8A34001_GPIO_5"] ;# Bank  69 VCCO - VCC1V2   - IO_L6P_T0U_N10_AD6P_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_5"] ;# Bank  69 VCCO - VCC1V2   - IO_L6P_T0U_N10_AD6P_69
# set_property PACKAGE_PIN L20        [get_ports "CLK_8A34001_GPIO_6"] ;# Bank  69 VCCO - VCC1V2   - IO_L5N_T0U_N9_AD14N_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_6"] ;# Bank  69 VCCO - VCC1V2   - IO_L5N_T0U_N9_AD14N_69
# set_property PACKAGE_PIN M20        [get_ports "CLK_8A34001_GPIO_7"] ;# Bank  69 VCCO - VCC1V2   - IO_L5P_T0U_N8_AD14P_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_7"] ;# Bank  69 VCCO - VCC1V2   - IO_L5P_T0U_N8_AD14P_69
# set_property PACKAGE_PIN N19        [get_ports "CLK_8A34001_GPIO_10"] ;# Bank  69 VCCO - VCC1V2   - IO_L3N_T0L_N5_AD15N_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_10"] ;# Bank  69 VCCO - VCC1V2   - IO_L3N_T0L_N5_AD15N_69
# set_property PACKAGE_PIN N20        [get_ports "CLK_8A34001_GPIO_11"] ;# Bank  69 VCCO - VCC1V2   - IO_L3P_T0L_N4_AD15P_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_11"] ;# Bank  69 VCCO - VCC1V2   - IO_L3P_T0L_N4_AD15P_69
# set_property PACKAGE_PIN P17        [get_ports "CLK_8A34001_GPIO_12"] ;# Bank  69 VCCO - VCC1V2   - IO_L2N_T0L_N3_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_12"] ;# Bank  69 VCCO - VCC1V2   - IO_L2N_T0L_N3_69
# set_property PACKAGE_PIN R17        [get_ports "CLK_8A34001_GPIO_13"] ;# Bank  69 VCCO - VCC1V2   - IO_L2P_T0L_N2_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_13"] ;# Bank  69 VCCO - VCC1V2   - IO_L2P_T0L_N2_69
# set_property PACKAGE_PIN R19        [get_ports "CLK_8A34001_GPIO_14"] ;# Bank  69 VCCO - VCC1V2   - IO_L1N_T0L_N1_DBC_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_14"] ;# Bank  69 VCCO - VCC1V2   - IO_L1N_T0L_N1_DBC_69
# set_property PACKAGE_PIN R20        [get_ports "CLK_8A34001_GPIO_15"] ;# Bank  69 VCCO - VCC1V2   - IO_L1P_T0L_N0_DBC_69
# set_property IOSTANDARD  LVCMOS12   [get_ports "CLK_8A34001_GPIO_15"] ;# Bank  69 VCCO - VCC1V2   - IO_L1P_T0L_N0_DBC_69

# SFP connections
set_property PACKAGE_PIN AC42     [get_ports "SFP0_RX_N"] ;# Bank 128 - MGTYRXN0_128
set_property PACKAGE_PIN AC41     [get_ports "SFP0_RX_P"] ;# Bank 128 - MGTYRXP0_128
set_property PACKAGE_PIN V39      [get_ports "SFP0_TX_N"] ;# Bank 128 - MGTYTXN0_128
set_property PACKAGE_PIN V38      [get_ports "SFP0_TX_P"] ;# Bank 128 - MGTYTXP0_128
set_property PACKAGE_PIN AB40     [get_ports "SFP1_RX_N"] ;# Bank 128 - MGTYRXN1_128
set_property PACKAGE_PIN AB39     [get_ports "SFP1_RX_P"] ;# Bank 128 - MGTYRXP1_128
set_property PACKAGE_PIN U37      [get_ports "SFP1_TX_N"] ;# Bank 128 - MGTYTXN1_128
set_property PACKAGE_PIN U36      [get_ports "SFP1_TX_P"] ;# Bank 128 - MGTYTXP1_128
set_property PACKAGE_PIN W42      [get_ports "SFP2_RX_N"] ;# Bank 129 - MGTYRXN0_129
set_property PACKAGE_PIN W41      [get_ports "SFP2_RX_P"] ;# Bank 129 - MGTYRXP0_129
set_property PACKAGE_PIN P39      [get_ports "SFP2_TX_N"] ;# Bank 129 - MGTYTXN0_129
set_property PACKAGE_PIN P38      [get_ports "SFP2_TX_P"] ;# Bank 129 - MGTYTXP0_129
set_property PACKAGE_PIN U42      [get_ports "SFP3_RX_N"] ;# Bank 129 - MGTYRXN1_129
set_property PACKAGE_PIN U41      [get_ports "SFP3_RX_P"] ;# Bank 129 - MGTYRXP1_129
set_property PACKAGE_PIN N37      [get_ports "SFP3_TX_N"] ;# Bank 129 - MGTYTXN1_129
set_property PACKAGE_PIN N36      [get_ports "SFP3_TX_P"] ;# Bank 129 - MGTYTXP1_129

# FMC connector clocks
set_property PACKAGE_PIN AR26     [get_ports "FMCP_CLK1_M2C_N"] ;# Bank  66 VCCO - VADJ_FMC - IO_L12N_T1U_N11_GC_66
set_property IOSTANDARD  LVDS     [get_ports "FMCP_CLK1_M2C_N"] ;# Bank  66 VCCO - VADJ_FMC - IO_L12N_T1U_N11_GC_66
set_property PACKAGE_PIN AP26     [get_ports "FMCP_CLK1_M2C_P"] ;# Bank  66 VCCO - VADJ_FMC - IO_L12P_T1U_N10_GC_66
set_property IOSTANDARD  LVDS     [get_ports "FMCP_CLK1_M2C_P"] ;# Bank  66 VCCO - VADJ_FMC - IO_L12P_T1U_N10_GC_66

# DIP switches
# set_property PACKAGE_PIN AY10      [get_ports {GPIO_DIP_SW[0]}] ;# Bank  84 VCCO - VCC1V8   - IO_L4N_AD8N_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[0]}] ;# Bank  84 VCCO - VCC1V8   - IO_L4N_AD8N_84
# set_property PACKAGE_PIN AY11      [get_ports {GPIO_DIP_SW[1]}] ;# Bank  84 VCCO - VCC1V8   - IO_L4P_AD8P_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[1]}] ;# Bank  84 VCCO - VCC1V8   - IO_L4P_AD8P_84
# set_property PACKAGE_PIN BA9       [get_ports {GPIO_DIP_SW[2]}] ;# Bank  84 VCCO - VCC1V8   - IO_L3N_AD9N_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[2]}] ;# Bank  84 VCCO - VCC1V8   - IO_L3N_AD9N_84
# set_property PACKAGE_PIN AY9       [get_ports {GPIO_DIP_SW[3]}] ;# Bank  84 VCCO - VCC1V8   - IO_L3P_AD9P_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[3]}] ;# Bank  84 VCCO - VCC1V8   - IO_L3P_AD9P_84
# set_property PACKAGE_PIN BB9       [get_ports {GPIO_DIP_SW[4]}] ;# Bank  84 VCCO - VCC1V8   - IO_L2N_AD10N_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[4]}] ;# Bank  84 VCCO - VCC1V8   - IO_L2N_AD10N_84
# set_property PACKAGE_PIN BA10      [get_ports {GPIO_DIP_SW[5]}] ;# Bank  84 VCCO - VCC1V8   - IO_L2P_AD10P_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[5]}] ;# Bank  84 VCCO - VCC1V8   - IO_L2P_AD10P_84
# set_property PACKAGE_PIN BB10      [get_ports {GPIO_DIP_SW[6]}] ;# Bank  84 VCCO - VCC1V8   - IO_L1N_AD11N_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[6]}] ;# Bank  84 VCCO - VCC1V8   - IO_L1N_AD11N_84
# set_property PACKAGE_PIN BB11      [get_ports {GPIO_DIP_SW[7]}] ;# Bank  84 VCCO - VCC1V8   - IO_L1P_AD11P_84
# set_property IOSTANDARD  LVCMOS18  [get_ports {GPIO_DIP_SW[7]}] ;# Bank  84 VCCO - VCC1V8   - IO_L1P_AD11P_84

# Button pad
# set_property PACKAGE_PIN H10       [get_ports "GPIO_SW_S"] ;# Bank  89 VCCO - VCC1V8   - IO_L3P_AD9P_89
# set_property IOSTANDARD  LVCMOS18  [get_ports "GPIO_SW_S"] ;# Bank  89 VCCO - VCC1V8   - IO_L3P_AD9P_89
# set_property PACKAGE_PIN J11       [get_ports "GPIO_SW_N"] ;# Bank  89 VCCO - VCC1V8   - IO_L2N_AD10N_89
# set_property IOSTANDARD  LVCMOS18  [get_ports "GPIO_SW_N"] ;# Bank  89 VCCO - VCC1V8   - IO_L2N_AD10N_89
# set_property PACKAGE_PIN J12       [get_ports "GPIO_SW_E"] ;# Bank  89 VCCO - VCC1V8   - IO_L2P_AD10P_89
# set_property IOSTANDARD  LVCMOS18  [get_ports "GPIO_SW_E"] ;# Bank  89 VCCO - VCC1V8   - IO_L2P_AD10P_89
# set_property PACKAGE_PIN K11       [get_ports "GPIO_SW_C"] ;# Bank  89 VCCO - VCC1V8   - IO_L1N_AD11N_89
# set_property IOSTANDARD  LVCMOS18  [get_ports "GPIO_SW_C"] ;# Bank  89 VCCO - VCC1V8   - IO_L1N_AD11N_89
# set_property PACKAGE_PIN K12       [get_ports "GPIO_SW_W"] ;# Bank  89 VCCO - VCC1V8   - IO_L1P_AD11P_89
# set_property IOSTANDARD  LVCMOS18  [get_ports "GPIO_SW_W"] ;# Bank  89 VCCO - VCC1V8   - IO_L1P_AD11P_89

# GPIO exposed on the RF daughterboard
# Choosing arbitrarily for now to make the DACIO outputs and the ADCIO inputs
set_property PACKAGE_PIN F13     [get_ports {DACIO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[0]}]
set_property PACKAGE_PIN F14     [get_ports {DACIO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[1]}]
set_property PACKAGE_PIN A14     [get_ports {DACIO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[2]}]
set_property PACKAGE_PIN A15     [get_ports {DACIO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[3]}]
set_property PACKAGE_PIN C16     [get_ports {DACIO[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[4]}]
set_property PACKAGE_PIN D16     [get_ports {DACIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[5]}]
set_property PACKAGE_PIN E15     [get_ports {DACIO[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[6]}]
set_property PACKAGE_PIN E16     [get_ports {DACIO[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[7]}]
set_property PACKAGE_PIN B15     [get_ports {DACIO[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[8]}]
set_property PACKAGE_PIN B16     [get_ports {DACIO[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[9]}]
set_property PACKAGE_PIN C14     [get_ports {DACIO[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[10]}]
set_property PACKAGE_PIN C15     [get_ports {DACIO[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[11]}]
set_property PACKAGE_PIN E14     [get_ports {DACIO[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[12]}]
set_property PACKAGE_PIN F15     [get_ports {DACIO[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[13]}]
set_property PACKAGE_PIN B12     [get_ports {DACIO[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[14]}]
set_property PACKAGE_PIN B13     [get_ports {DACIO[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DACIO[15]}]

set_property PACKAGE_PIN AP10    [get_ports {ADCIO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[0]}]
set_property PACKAGE_PIN AP11    [get_ports {ADCIO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[1]}]
set_property PACKAGE_PIN AR11    [get_ports {ADCIO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[2]}]
set_property PACKAGE_PIN AP12    [get_ports {ADCIO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[3]}]
set_property PACKAGE_PIN AT10    [get_ports {ADCIO[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[4]}]
set_property PACKAGE_PIN AR10    [get_ports {ADCIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[5]}]
set_property PACKAGE_PIN AT12    [get_ports {ADCIO[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[6]}]
set_property PACKAGE_PIN AR12    [get_ports {ADCIO[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[7]}]
set_property PACKAGE_PIN AU11    [get_ports {ADCIO[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[8]}]
set_property PACKAGE_PIN AU12    [get_ports {ADCIO[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[9]}]
set_property PACKAGE_PIN AV10    [get_ports {ADCIO[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[10]}]
set_property PACKAGE_PIN AU10    [get_ports {ADCIO[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[11]}]
set_property PACKAGE_PIN AW9     [get_ports {ADCIO[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[12]}]
set_property PACKAGE_PIN AV9     [get_ports {ADCIO[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[13]}]
set_property PACKAGE_PIN AW11    [get_ports {ADCIO[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[14]}]
set_property PACKAGE_PIN AV11    [get_ports {ADCIO[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADCIO[15]}]

# DDR signals
set_property PACKAGE_PIN F17      [get_ports "DDR4_C0_SYS_CLK_clk_n"]   ;
set_property PACKAGE_PIN G17      [get_ports "DDR4_C0_SYS_CLK_clk_p"]   ;

set_property PACKAGE_PIN G20      [get_ports "DDR4_C0_ck_c[0]"] ;
set_property PACKAGE_PIN H20      [get_ports "DDR4_C0_ck_t[0]"] ;
set_property PACKAGE_PIN A18      [get_ports "DDR4_C0_cke[0]"] ;
set_property PACKAGE_PIN B18      [get_ports "DDR4_C0_reset_n"] ;
set_property IOSTANDARD  LVCMOS12 [get_ports "DDR4_C0_reset_n"] ;

set_property PACKAGE_PIN A20      [get_ports "DDR4_C0_cs_n[0]"] ; # CS TOP
set_property PACKAGE_PIN P19      [get_ports "DDR4_C0_cs_n[1]"] ; # CS BOT

#set_property PACKAGE_PIN B17      [get_ports "DDR4_C0_alert_n"] ;
set_property PACKAGE_PIN C18      [get_ports "DDR4_C0_act_n"] ;
set_property PACKAGE_PIN C19      [get_ports "DDR4_C0_odt"] ;
#set_property PACKAGE_PIN C20      [get_ports "DDR4_C0_parity"] ;

set_property PACKAGE_PIN D21      [get_ports "DDR4_C0_adr[0]"] ;
set_property PACKAGE_PIN E19      [get_ports "DDR4_C0_adr[1]"] ;
set_property PACKAGE_PIN D18      [get_ports "DDR4_C0_adr[2]"] ;
set_property PACKAGE_PIN D19      [get_ports "DDR4_C0_adr[3]"] ;
set_property PACKAGE_PIN E20      [get_ports "DDR4_C0_adr[4]"] ;
set_property PACKAGE_PIN E21      [get_ports "DDR4_C0_adr[5]"] ;
set_property PACKAGE_PIN D17      [get_ports "DDR4_C0_adr[6]"] ;
set_property PACKAGE_PIN E17      [get_ports "DDR4_C0_adr[7]"] ;
set_property PACKAGE_PIN F20      [get_ports "DDR4_C0_adr[8]"] ;
set_property PACKAGE_PIN G21      [get_ports "DDR4_C0_adr[9]"] ;
set_property PACKAGE_PIN F18      [get_ports "DDR4_C0_adr[10]"] ;
set_property PACKAGE_PIN F19      [get_ports "DDR4_C0_adr[11]"] ;
set_property PACKAGE_PIN J17      [get_ports "DDR4_C0_adr[12]"] ;
set_property PACKAGE_PIN J18      [get_ports "DDR4_C0_adr[13]"] ;

set_property PACKAGE_PIN A17      [get_ports "DDR4_C0_adr[14]"] ; #WE
set_property PACKAGE_PIN A19      [get_ports "DDR4_C0_adr[15]"] ; #CAS
set_property PACKAGE_PIN C21      [get_ports "DDR4_C0_adr[16]"] ; #RAS

set_property PACKAGE_PIN G18      [get_ports "DDR4_C0_ba[0]"] ;
set_property PACKAGE_PIN H18      [get_ports "DDR4_C0_ba[1]"] ;
set_property PACKAGE_PIN B20      [get_ports "DDR4_C0_bg[0]"] ;
set_property PACKAGE_PIN B21      [get_ports "DDR4_C0_bg[1]"] ;

set_property PACKAGE_PIN D22      [get_ports "DDR4_C0_dqs_c[0]"] ;
set_property PACKAGE_PIN E22      [get_ports "DDR4_C0_dqs_t[0]"] ;
set_property PACKAGE_PIN B23      [get_ports "DDR4_C0_dqs_c[1]"] ;
set_property PACKAGE_PIN B22      [get_ports "DDR4_C0_dqs_t[1]"] ;
set_property PACKAGE_PIN G23      [get_ports "DDR4_C0_dqs_c[2]"] ;
set_property PACKAGE_PIN H23      [get_ports "DDR4_C0_dqs_t[2]"] ;
set_property PACKAGE_PIN P24      [get_ports "DDR4_C0_dqs_c[3]"] ;
set_property PACKAGE_PIN R24      [get_ports "DDR4_C0_dqs_t[3]"] ;

set_property PACKAGE_PIN C23      [get_ports "DDR4_C0_dq[0]"] ;
set_property PACKAGE_PIN F24      [get_ports "DDR4_C0_dq[1]"] ;
set_property PACKAGE_PIN D26      [get_ports "DDR4_C0_dq[2]"] ;
set_property PACKAGE_PIN E26      [get_ports "DDR4_C0_dq[3]"] ;
set_property PACKAGE_PIN D23      [get_ports "DDR4_C0_dq[4]"] ;
set_property PACKAGE_PIN G25      [get_ports "DDR4_C0_dq[5]"] ;
set_property PACKAGE_PIN F25      [get_ports "DDR4_C0_dq[6]"] ;
set_property PACKAGE_PIN F23      [get_ports "DDR4_C0_dq[7]"] ;
set_property PACKAGE_PIN B25      [get_ports "DDR4_C0_dq[8]"] ;
set_property PACKAGE_PIN A23      [get_ports "DDR4_C0_dq[9]"] ;
set_property PACKAGE_PIN A24      [get_ports "DDR4_C0_dq[10]"] ;
set_property PACKAGE_PIN A22      [get_ports "DDR4_C0_dq[11]"] ;
set_property PACKAGE_PIN D24      [get_ports "DDR4_C0_dq[12]"] ;
set_property PACKAGE_PIN C25      [get_ports "DDR4_C0_dq[13]"] ;
set_property PACKAGE_PIN A25      [get_ports "DDR4_C0_dq[14]"] ;
set_property PACKAGE_PIN C24      [get_ports "DDR4_C0_dq[15]"] ;
set_property PACKAGE_PIN J24      [get_ports "DDR4_C0_dq[16]"] ;
set_property PACKAGE_PIN F22      [get_ports "DDR4_C0_dq[17]"] ;
set_property PACKAGE_PIN K24      [get_ports "DDR4_C0_dq[18]"] ;
set_property PACKAGE_PIN G22      [get_ports "DDR4_C0_dq[19]"] ;
set_property PACKAGE_PIN J22      [get_ports "DDR4_C0_dq[20]"] ;
set_property PACKAGE_PIN H24      [get_ports "DDR4_C0_dq[21]"] ;
set_property PACKAGE_PIN K22      [get_ports "DDR4_C0_dq[22]"] ;
set_property PACKAGE_PIN H25      [get_ports "DDR4_C0_dq[23]"] ;
set_property PACKAGE_PIN P23      [get_ports "DDR4_C0_dq[24]"] ;
set_property PACKAGE_PIN R22      [get_ports "DDR4_C0_dq[25]"] ;
set_property PACKAGE_PIN N24      [get_ports "DDR4_C0_dq[26]"] ;
set_property PACKAGE_PIN N21      [get_ports "DDR4_C0_dq[27]"] ;
set_property PACKAGE_PIN M23      [get_ports "DDR4_C0_dq[28]"] ;
set_property PACKAGE_PIN N23      [get_ports "DDR4_C0_dq[29]"] ;
set_property PACKAGE_PIN M22      [get_ports "DDR4_C0_dq[30]"] ;
set_property PACKAGE_PIN M21      [get_ports "DDR4_C0_dq[31]"] ;

set_property PACKAGE_PIN H26      [get_ports "DDR4_C0_dm_n[0]"] ;
set_property PACKAGE_PIN C26      [get_ports "DDR4_C0_dm_n[1]"] ;
set_property PACKAGE_PIN L23      [get_ports "DDR4_C0_dm_n[2]"] ;
set_property PACKAGE_PIN R21      [get_ports "DDR4_C0_dm_n[3]"] ;

set_property PACKAGE_PIN AR19     [get_ports "DDR4_C1_SYS_CLK_clk_n"]   ;
set_property PACKAGE_PIN AR20     [get_ports "DDR4_C1_SYS_CLK_clk_p"]   ;

set_property PACKAGE_PIN AN20     [get_ports "DDR4_C1_ck_c[0]"] ;
set_property PACKAGE_PIN AN21     [get_ports "DDR4_C1_ck_t[0]"] ;
set_property PACKAGE_PIN AH19     [get_ports "DDR4_C1_cke[0]"] ;
set_property PACKAGE_PIN AH20     [get_ports "DDR4_C1_reset_n"] ;
set_property IOSTANDARD  LVCMOS12 [get_ports "DDR4_C1_reset_n"] ;

set_property PACKAGE_PIN AH21     [get_ports "DDR4_C1_cs_n[0]"] ;     # CS TOP
set_property PACKAGE_PIN AY19     [get_ports "DDR4_C1_cs_n[1]"] ;     # CS BOT

#set_property PACKAGE_PIN AH18     [get_ports "DDR4_C1_alert_n"] ;
set_property PACKAGE_PIN AK17     [get_ports "DDR4_C1_act_n"] ;
set_property PACKAGE_PIN AJ17     [get_ports "DDR4_C1_odt"] ;
#set_property PACKAGE_PIN AL20     [get_ports "DDR4_C1_parity"] ;

set_property PACKAGE_PIN AK19     [get_ports "DDR4_C1_adr[0]"] ;
set_property PACKAGE_PIN AM17     [get_ports "DDR4_C1_adr[1]"] ;
set_property PACKAGE_PIN AL17     [get_ports "DDR4_C1_adr[2]"] ;
set_property PACKAGE_PIN AL18     [get_ports "DDR4_C1_adr[3]"] ;
set_property PACKAGE_PIN AM20     [get_ports "DDR4_C1_adr[4]"] ;
set_property PACKAGE_PIN AM21     [get_ports "DDR4_C1_adr[5]"] ;
set_property PACKAGE_PIN AN18     [get_ports "DDR4_C1_adr[6]"] ;
set_property PACKAGE_PIN AM18     [get_ports "DDR4_C1_adr[7]"] ;
set_property PACKAGE_PIN AP19     [get_ports "DDR4_C1_adr[8]"] ;
set_property PACKAGE_PIN AN19     [get_ports "DDR4_C1_adr[9]"] ;
set_property PACKAGE_PIN AP17     [get_ports "DDR4_C1_adr[10]"] ;
set_property PACKAGE_PIN AP18     [get_ports "DDR4_C1_adr[11]"] ;
set_property PACKAGE_PIN AU18     [get_ports "DDR4_C1_adr[12]"] ;
set_property PACKAGE_PIN AT18     [get_ports "DDR4_C1_adr[13]"] ;

set_property PACKAGE_PIN AJ18     [get_ports "DDR4_C1_adr[14]"] ;    #WE
set_property PACKAGE_PIN AJ21     [get_ports "DDR4_C1_adr[15]"] ;    #CAS
set_property PACKAGE_PIN AL19     [get_ports "DDR4_C1_adr[16]"] ;    #RAS

set_property PACKAGE_PIN AT19     [get_ports "DDR4_C1_ba[0]"] ;
set_property PACKAGE_PIN AT20     [get_ports "DDR4_C1_ba[1]"] ;
set_property PACKAGE_PIN AK20     [get_ports "DDR4_C1_bg[0]"] ;
set_property PACKAGE_PIN AK21     [get_ports "DDR4_C1_bg[1]"] ;

set_property PACKAGE_PIN AT14     [get_ports "DDR4_C1_dqs_c[0]"] ;
set_property PACKAGE_PIN AR14     [get_ports "DDR4_C1_dqs_t[0]"] ;
set_property PACKAGE_PIN AM15     [get_ports "DDR4_C1_dqs_c[1]"] ;
set_property PACKAGE_PIN AL15     [get_ports "DDR4_C1_dqs_t[1]"] ;
set_property PACKAGE_PIN AW14     [get_ports "DDR4_C1_dqs_c[2]"] ;
set_property PACKAGE_PIN AV14     [get_ports "DDR4_C1_dqs_t[2]"] ;
set_property PACKAGE_PIN BB15     [get_ports "DDR4_C1_dqs_c[3]"] ;
set_property PACKAGE_PIN BB16     [get_ports "DDR4_C1_dqs_t[3]"] ;

set_property PACKAGE_PIN AR17     [get_ports "DDR4_C1_dq[0]"] ;
set_property PACKAGE_PIN AT15     [get_ports "DDR4_C1_dq[1]"] ;
set_property PACKAGE_PIN AR16     [get_ports "DDR4_C1_dq[2]"] ;
set_property PACKAGE_PIN AT17     [get_ports "DDR4_C1_dq[3]"] ;
set_property PACKAGE_PIN AR15     [get_ports "DDR4_C1_dq[4]"] ;
set_property PACKAGE_PIN AU15     [get_ports "DDR4_C1_dq[5]"] ;
set_property PACKAGE_PIN AN13     [get_ports "DDR4_C1_dq[6]"] ;
set_property PACKAGE_PIN AP13     [get_ports "DDR4_C1_dq[7]"] ;
set_property PACKAGE_PIN AN15     [get_ports "DDR4_C1_dq[8]"] ;
set_property PACKAGE_PIN AJ14     [get_ports "DDR4_C1_dq[9]"] ;
set_property PACKAGE_PIN AM13     [get_ports "DDR4_C1_dq[10]"] ;
set_property PACKAGE_PIN AK14     [get_ports "DDR4_C1_dq[11]"] ;
set_property PACKAGE_PIN AK16     [get_ports "DDR4_C1_dq[12]"] ;
set_property PACKAGE_PIN AK15     [get_ports "DDR4_C1_dq[13]"] ;
set_property PACKAGE_PIN AM16     [get_ports "DDR4_C1_dq[14]"] ;
set_property PACKAGE_PIN AL14     [get_ports "DDR4_C1_dq[15]"] ;
set_property PACKAGE_PIN AV13     [get_ports "DDR4_C1_dq[16]"] ;
set_property PACKAGE_PIN AV16     [get_ports "DDR4_C1_dq[17]"] ;
set_property PACKAGE_PIN AU13     [get_ports "DDR4_C1_dq[18]"] ;
set_property PACKAGE_PIN AW17     [get_ports "DDR4_C1_dq[19]"] ;
set_property PACKAGE_PIN AW13     [get_ports "DDR4_C1_dq[20]"] ;
set_property PACKAGE_PIN AW16     [get_ports "DDR4_C1_dq[21]"] ;
set_property PACKAGE_PIN AT13     [get_ports "DDR4_C1_dq[22]"] ;
set_property PACKAGE_PIN AV15     [get_ports "DDR4_C1_dq[23]"] ;
set_property PACKAGE_PIN AY15     [get_ports "DDR4_C1_dq[24]"] ;
set_property PACKAGE_PIN BA15     [get_ports "DDR4_C1_dq[25]"] ;
set_property PACKAGE_PIN AY14     [get_ports "DDR4_C1_dq[26]"] ;
set_property PACKAGE_PIN BA14     [get_ports "DDR4_C1_dq[27]"] ;
set_property PACKAGE_PIN BA12     [get_ports "DDR4_C1_dq[28]"] ;
set_property PACKAGE_PIN BB17     [get_ports "DDR4_C1_dq[29]"] ;
set_property PACKAGE_PIN BA13     [get_ports "DDR4_C1_dq[30]"] ;
set_property PACKAGE_PIN BA17     [get_ports "DDR4_C1_dq[31]"] ;

set_property PACKAGE_PIN AU17     [get_ports "DDR4_C1_dm_n[0]"] ;
set_property PACKAGE_PIN AN16     [get_ports "DDR4_C1_dm_n[1]"] ;
set_property PACKAGE_PIN AY17     [get_ports "DDR4_C1_dm_n[2]"] ;
set_property PACKAGE_PIN BB13     [get_ports "DDR4_C1_dm_n[3]"] ;
