`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: Yale University
// Engineer: William Kalfus
// 
// Create Date: 11/10/2022 03:24:36 PM
// Design Name: acadia
// Module Name: acadia_tb
// Project Name: acadia
// Target Devices: ZCU216
// Tool Versions: 2020.2
// Description: A testbench intended to verify the functionality of the complete
//              block design, including exposing internal signals to verify 
//              internal signal processing, latencies, and timing relationships.
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module acadia_tb();
    
    // -------------------------- Declare many signals that will be useful for debugging ----------------------------
    
    // DAC clock generated by external source (in this case, manually in the testbench)
    reg          dac_clk_p;

    // PS signals
    wire         ps_pl_clk;
    wire         ps_pl_resetn;
    wire [90:0]  ps_gpio_out;
    
    // Sequencer clock generated by clocking wizard
    wire         seq_clk;
    
    // Clock generated by RF data converter
    wire         clk_dac1;
    
    // Sequencer resetn and run signals
    reg          debug_seq_nrst;
    reg          debug_seq_run;
    
    // Sequencer resetn and run signals
    wire         seq_nrst;
    wire         seq_run;
    
    // Clock wizard outputs
    wire         clk_wiz_locked;
    wire         clk_wiz_clk_300;

    // Internal simulation signals
    reg          resp;
    
    reg [511:0]  cache_data;
    
    // -------------------------- Assign the signals to their companions in the block design using hierarchical references ----------------------------

    // Connect some of our test signals to internal pins in the block design
    assign ps_pl_clk        = acadia_tb.uut.ps.pl_clk0;
    assign ps_pl_resetn     = acadia_tb.uut.ps.pl_resetn0;
    assign ps_gpio_out      = acadia_tb.uut.ps.emio_gpio_o;
    
    assign seq_clk          = acadia_tb.uut.hedgehog.seq_clk;
    assign clk_dac1         = acadia_tb.uut.hedgehog.rfdc.clk_dac1;
    
    // Sequencer resetn and run signals
    assign seq_nrst = acadia_tb.uut.xpm_cdc_seq_rst.dest_rst_out;
    assign seq_run = acadia_tb.uut.xpm_cdc_seq_run.dest_rst_out;
    
//    // Clock wizard outputs
    assign clk_wiz_locked  = acadia_tb.uut.hedgehog.clk_wiz.locked;
    assign clk_wiz_clk_300 = acadia_tb.uut.hedgehog.clk_wiz.clk_300;  

    // -------------------------- Drive the DAC clock ----------------------------
    initial begin       
        dac_clk_p = 1'b0;
    end
    
    always begin
        #1.66666666667 dac_clk_p = ~dac_clk_p;
    end

    // -------------------------- Instantiate the block design ----------------------------
    acadia_bd uut
       (.DDR4_C0_SYS_CLK_clk_n(),
        .DDR4_C0_SYS_CLK_clk_p(),
        .DDR4_C0_act_n(),
        .DDR4_C0_adr(),
        .DDR4_C0_ba(),
        .DDR4_C0_bg(),
        .DDR4_C0_ck_c(),
        .DDR4_C0_ck_t(),
        .DDR4_C0_cke(),
        .DDR4_C0_cs_n(),
        .DDR4_C0_dm_n(),
        .DDR4_C0_dq(),
        .DDR4_C0_dqs_c(),
        .DDR4_C0_dqs_t(),
        .DDR4_C0_odt(),
        .DDR4_C0_reset_n(),
        .DDR4_C1_SYS_CLK_clk_n(),
        .DDR4_C1_SYS_CLK_clk_p(),
        .DDR4_C1_act_n(),
        .DDR4_C1_adr(),
        .DDR4_C1_ba(),
        .DDR4_C1_bg(),
        .DDR4_C1_ck_c(),
        .DDR4_C1_ck_t(),
        .DDR4_C1_cke(),
        .DDR4_C1_cs_n(),
        .DDR4_C1_dm_n(),
        .DDR4_C1_dq(),
        .DDR4_C1_dqs_c(),
        .DDR4_C1_dqs_t(),
        .DDR4_C1_odt(),
        .DDR4_C1_reset_n(),
        .dac2_clk_clk_n(~dac_clk_p),
        .dac2_clk_clk_p(dac_clk_p),
        .debug_clk(dac_clk_p),
        .debug_seq_nrst(debug_seq_nrst),
        .debug_seq_run(debug_seq_run),
        .sysref_in_diff_n(),
        .sysref_in_diff_p(),
        .vin00_v_n(),
        .vin00_v_p(),
        .vin01_v_n(),
        .vin01_v_p(),
        .vin02_v_n(),
        .vin02_v_p(),
        .vin03_v_n(),
        .vin03_v_p(),
        .vin10_v_n(),
        .vin10_v_p(),
        .vin11_v_n(),
        .vin11_v_p(),
        .vin12_v_n(),
        .vin12_v_p(),
        .vin13_v_n(),
        .vin13_v_p(),
        .vin20_v_n(),
        .vin20_v_p(),
        .vin21_v_n(),
        .vin21_v_p(),
        .vin22_v_n(),
        .vin22_v_p(),
        .vin23_v_n(),
        .vin23_v_p(),
        .vin30_v_n(),
        .vin30_v_p(),
        .vin31_v_n(),
        .vin31_v_p(),
        .vin32_v_n(),
        .vin32_v_p(),
        .vin33_v_n(),
        .vin33_v_p(),
        .vout00_v_n(),
        .vout00_v_p(),
        .vout01_v_n(),
        .vout01_v_p(),
        .vout02_v_n(),
        .vout02_v_p(),
        .vout03_v_n(),
        .vout03_v_p(),
        .vout10_v_n(),
        .vout10_v_p(),
        .vout11_v_n(),
        .vout11_v_p(),
        .vout12_v_n(),
        .vout12_v_p(),
        .vout13_v_n(),
        .vout13_v_p(),
        .vout20_v_n(),
        .vout20_v_p(),
        .vout21_v_n(),
        .vout21_v_p(),
        .vout22_v_n(),
        .vout22_v_p(),
        .vout23_v_n(),
        .vout23_v_p(),
        .vout30_v_n(),
        .vout30_v_p(),
        .vout31_v_n(),
        .vout31_v_p(),
        .vout32_v_n(),
        .vout32_v_p(),
        .vout33_v_n(),
        .vout33_v_p());
    
    // -------------------------- Simulate the PS writing commands to run the testbench ----------------------------
    initial begin
        debug_seq_run = 1'b0;
        debug_seq_nrst = 1'b0;
        
        // Reset everything
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b1);
        repeat(30) @(posedge dac_clk_p);
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b0);
        acadia_tb.uut.ps.inst.fpga_soft_reset(4'h1);
        repeat(30) @(posedge dac_clk_p);
        acadia_tb.uut.ps.inst.por_srstb_reset(1'b1);
        acadia_tb.uut.ps.inst.fpga_soft_reset(4'h0);
        
        // Wait for the clocks to lock
        @(posedge clk_wiz_locked);
        
        repeat(30) @(posedge dac_clk_p);
        
        
        // Add AXI data loading here!
        
        
        repeat(30) @(posedge dac_clk_p);
        
        debug_seq_run = 1'b0;
        debug_seq_nrst = 1'b1;
        
        repeat(5) @(posedge dac_clk_p);
        
        debug_seq_run = 1'b1;
        debug_seq_nrst = 1'b1;
        
        // Wait until the sequencer sets the PS gpio at the end of the test
        @(posedge acadia_tb.uut.hedgehog.PS_GPIO_IN[0]);
        
        repeat(5) @(posedge dac_clk_p);
        
        // Read any data produced by the simulated logic and stored somewhere on the AXI network
        
        repeat(5) @(posedge dac_clk_p);
        
        $finish;
    end


endmodule
