----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 10/07/2023 03:53:08 PM
-- Design Name: 
-- Module Name: acadia_bus_xcvr - rtl
-- Project Name: acadia
-- Target Devices: ZCU216
-- Tool Versions: 2020.2
-- Description: A lightweight module for interface GTY transceivers to a 
--    memory bus. 
--
--    The module exposes one concatenated control and monitor port for use with an external controller
--    NOT operating on the clock recovered or generated by any MGT logic. This port is for 
--    ensuring proper reset and bring-up of the MGT logic. The signals are grouped into a 
--    concatenated into a single port rather than broken out individually in order to ease integration with 
--    the PS GPIO controller or an AXI GPIO module.
--
--    External control port signals:
--
--      Bit 0: w: gtwiz_userclk_tx_reset
--               r: gtwiz_userclk_tx_active
--
--        Bit 1: w: gtwiz_userclk_rx_reset
--               r: gtwiz_userclk_rx_active
--        
--        Bit 2: w: gtwiz_reset_all
--               r: gtwiz_reset_rx_cdr_stable
--
--        Bit 3: w: gtwiz_reset_tx_pll_and_datapath
--               r: gtwiz_reset_tx_done
--          
--        Bit 4: w: gtwiz_reset_tx_datapath
--               r: txpmaresetdone
--
--        Bit 5: w: gtwiz_reset_rx_pll_and_datapath
--               r: gtwiz_reset_rx_done
--
--        Bit 6: w: gtwiz_reset_rx_datapath
--               r: rxpmaresetdone
--
--        Bit 7: w: no effect
--                r: rxprgdivresetdone
--
--        Bit 8: w: no effect
--                r: gtpowergood
--
--    Register 0: Real-time Control and Status signals
--
--        Bit 0: w: rxcommadeten
--               r: 0
--
--        Bit 1: w: rxmcommaalignen
--               r: 0
--        
--        Bit 2: w: rxpcommaalignen
--               r: 0
--
--        Bit 3: w: no effect
--               r: RX FIFO empty
--
--        Bit 4: w: no effect
--               r: RX FIFO overflow
--
--        Bit 5: w: no effect
--               r: TX FIFO full
--
--        Bits 7-6: w: Reserved (no effect)
--                  r: 0
--
--        Bits 11-8: w: rxprbssel
--                  r: 0
--
--        Bits 15-12: w: txprbssel
--                   r: 0
--
--        Bit 16: w: rxcommadet (write 1 to clear, writing 0 has no effect)
--                r: rxcommadet (latched)
-- 
--        Bit 17: w: rxbyterealign (write 1 to clear, writing 0 has no effect)
--                r: rxbyterealign (latched)
--
--        Bit 18: w: rxprbserr (write 1 to clear, writing 0 has no effect)
--                r: rxprbserr (latched)
--
--        Bit 19: w: no effect
--                r: rxbyteisaligned
--
--        Bit 20: w: no effect
--                r: rxprbslocked
--
--        Bits 30-21: w: Reserved (no effect)
--                r: 0
--
--        Bit 31: w: Controller reset (write 1 to reset, writing 0 does nothing)
--                r: 0
--
--    Register 1: w: TX FIFO
--                r: no effect
--
--    Register 2: w: no effect
--                r: RX FIFO
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

library xpm;
use xpm.vcomponents.all;

entity acadia_gty_controller is
    generic (
        FIFO_DEPTH : positive := 16
    );
    port (
        -- Fabric clocks
        clk_freerun : in std_logic;
        tx_clk : out std_logic;
        rx_clk : out std_logic;

        rst : in std_logic;

        external_control: in std_logic_vector(8 downto 0);
        external_status: out std_logic_vector(8 downto 0);

        master_bus_clk   : in  std_logic;
        master_bus_mosi  : in  std_logic_vector(31 downto 0);
        master_bus_miso  : out std_logic_vector(31 downto 0);
        master_bus_addr  : in  std_logic_vector(31 downto 0);
        master_bus_we    : in  std_logic;
        master_bus_en    : in  std_logic;

        -- GT physical interface
        gt_tx_p : out std_logic;
        gt_tx_n : out std_logic;
        gt_rx_p : in  std_logic;
        gt_rx_n : in  std_logic;

        gt_refclk00 : in std_logic
    );
end acadia_gty_controller;

architecture rtl of acadia_gty_controller is

    component gtwizard_ultrascale_128
        port (
            gtwiz_userclk_tx_reset_in : in std_logic_vector(0 downto 0);
            gtwiz_userclk_tx_srcclk_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_tx_usrclk_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_tx_usrclk2_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_tx_active_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_rx_reset_in : in std_logic_vector(0 downto 0);
            gtwiz_userclk_rx_srcclk_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_rx_usrclk_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_rx_usrclk2_out : out std_logic_vector(0 downto 0);
            gtwiz_userclk_rx_active_out : out std_logic_vector(0 downto 0);
            gtwiz_reset_clk_freerun_in : in std_logic_vector(0 downto 0);
            gtwiz_reset_all_in : in std_logic_vector(0 downto 0);
            gtwiz_reset_tx_pll_and_datapath_in : in std_logic_vector(0 downto 0);
            gtwiz_reset_tx_datapath_in : in std_logic_vector(0 downto 0);
            gtwiz_reset_rx_pll_and_datapath_in : in std_logic_vector(0 downto 0);
            gtwiz_reset_rx_datapath_in : in std_logic_vector(0 downto 0);
            gtwiz_reset_rx_cdr_stable_out : out std_logic_vector(0 downto 0);
            gtwiz_reset_tx_done_out : out std_logic_vector(0 downto 0);
            gtwiz_reset_rx_done_out : out std_logic_vector(0 downto 0);
            gtwiz_userdata_tx_in : in std_logic_vector(31 downto 0);
            gtwiz_userdata_rx_out : out std_logic_vector(31 downto 0);
            gtrefclk00_in : in std_logic_vector(0 downto 0);
            qpll0outclk_out : out std_logic_vector(0 downto 0);
            qpll0outrefclk_out : out std_logic_vector(0 downto 0);
            gtyrxn_in : in std_logic_vector(0 downto 0);
            gtyrxp_in : in std_logic_vector(0 downto 0);
            rx8b10ben_in : in std_logic_vector(0 downto 0);
            rxcommadeten_in : in std_logic_vector(0 downto 0);
            rxmcommaalignen_in : in std_logic_vector(0 downto 0);
            rxpcommaalignen_in : in std_logic_vector(0 downto 0);
            rxprbscntreset_in : in std_logic_vector(0 downto 0);
            rxprbssel_in : in std_logic_vector(3 downto 0);
            tx8b10ben_in : in std_logic_vector(0 downto 0);
            txctrl0_in : in std_logic_vector(15 downto 0);
            txctrl1_in : in std_logic_vector(15 downto 0);
            txctrl2_in : in std_logic_vector(7 downto 0);
            txprbssel_in : in std_logic_vector(3 downto 0);
            gtpowergood_out : out std_logic_vector(0 downto 0);
            gtytxn_out : out std_logic_vector(0 downto 0);
            gtytxp_out : out std_logic_vector(0 downto 0);
            rxbyteisaligned_out : out std_logic_vector(0 downto 0);
            rxbyterealign_out : out std_logic_vector(0 downto 0);
            rxcommadet_out : out std_logic_vector(0 downto 0);
            rxctrl0_out : out std_logic_vector(15 downto 0);
            rxctrl1_out : out std_logic_vector(15 downto 0);
            rxctrl2_out : out std_logic_vector(7 downto 0);
            rxctrl3_out : out std_logic_vector(7 downto 0);
            rxpmaresetdone_out : out std_logic_vector(0 downto 0);
            rxprbserr_out : out std_logic_vector(0 downto 0);
            rxprbslocked_out : out std_logic_vector(0 downto 0);
            rxprgdivresetdone_out : out std_logic_vector(0 downto 0);
            rxrecclkout_out : out std_logic_vector(0 downto 0);
            txpmaresetdone_out : out std_logic_vector(0 downto 0)
        );
    end component;

    signal master_bus_clk_rst : std_logic;
    signal rxusrclk2_rst : std_logic;

    -- Internally-registered control signals
    signal rxcommadeten    : std_logic;
    signal rxmcommaalignen : std_logic;
    signal rxpcommaalignen : std_logic;
    signal rxprbssel       : std_logic_vector(3 downto 0);
    signal txprbssel       : std_logic_vector(3 downto 0);

    -- The same signals synchronized to the RXUSRCLK2 domain
    signal rxcommadeten_sync    : std_logic;
    signal rxmcommaalignen_sync : std_logic;
    signal rxpcommaalignen_sync : std_logic;
    signal rxprbssel_sync       : std_logic_vector(3 downto 0);
    signal txprbssel_sync       : std_logic_vector(3 downto 0);

    -- Latched status signals
    -- Signals with no suffix are in the master_bus_clk domain, 
    -- signals with the _sync suffix are in the rx_int_clk domain, 
    -- and signals with the _latch suffix are latches in the rx_int_clk domain
    signal rxcommadet          : std_logic;
    signal rxcommadet_sync     : std_logic;
    signal rxcommadet_latch    : std_logic;
    signal rxbyterealign       : std_logic;
    signal rxbyterealign_sync  : std_logic;
    signal rxbyterealign_latch : std_logic;
    signal rxprbserr           : std_logic;
    signal rxprbserr_sync      : std_logic;
    signal rxprbserr_latch     : std_logic;

    signal gt_latch_reset      : std_logic_vector(2 downto 0);
    signal gt_latch_reset_sync : std_logic_vector(gt_latch_reset'high downto 0);

    -- Non-latched status
    signal rxprbslocked         : std_logic;
    signal rxprbslocked_sync    : std_logic;
    signal rxbyteisaligned      : std_logic;
    signal rxbyteisaligned_sync : std_logic;

    signal rx_is_k_char          : std_logic_vector(3 downto 0);
    signal rx_invalid_data_error : std_logic_vector(3 downto 0);
    signal rx_disparity_error    : std_logic_vector(3 downto 0);
    signal rx_comma_detected     : std_logic_vector(3 downto 0);

    signal tx_is_k_char          : std_logic_vector(3 downto 0);

    signal gt_txdata : std_logic_vector(31 downto 0);
    signal gt_rxdata : std_logic_vector(31 downto 0);

    signal tx_clk_int : std_logic;
    signal rx_clk_int : std_logic;

begin

    -- Connect to the external port
    -- All of the inputs to the transceiver that come from the external port are already asynchronous,
    -- so we don't need to do any CDC (though if the GT wizard doesn't apply the right constraints, 
    -- we might need to manually add false paths).
    -- For the outputs to the external status port, we need to declare a false path so that whatever 
    -- it goes to doesn't try to get its timing.
    -- set_false_path -from [get_pins acadia_bd_i/hedgehog/acadia_gty_controller_128/inst/external_status]

    master_bus_clk_rst_sync: xpm_cdc_sync_rst
        generic map (
            DEST_SYNC_FF => 4,
            INIT => 1,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1
        )
        port map (
            src_rst => rst,

            dest_clk => master_bus_clk,
            dest_rst => master_bus_clk_rst
        );

    rxusrclk2_rst_sync: xpm_cdc_sync_rst
        generic map (
            DEST_SYNC_FF => 4,
            INIT => 1,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1
        )
        port map (
            src_rst => rst,

            dest_clk => rx_clk_int,
            dest_rst => rxusrclk2_rst
        );

    -- Latch some of the signals from the bus so that they stay asserted at
    -- the GTY interface
    control_proc: process(master_bus_clk) begin
        if rising_edge(master_bus_clk) then
            if(master_bus_clk_rst = '1') then
                rxcommadeten <= '1';
                rxmcommaalignen <= '1';
                rxpcommaalignen <= '1';
                rxprbssel <= (others => '0');
                txprbssel <= (others => '0');
            elsif(master_bus_en = '1' and master_bus_we = '1' and master_bus_addr(1 downto 0) = "00") then
                rxcommadeten <= master_bus_mosi(0);
                rxmcommaalignen <= master_bus_mosi(1);
                rxpcommaalignen <= master_bus_mosi(2);
                rxprbssel <= master_bus_mosi(11 downto 8);
                txprbssel <= master_bus_mosi(15 downto 12);
            end if;
        end if;
    end process control_proc;

    bus_rd_proc: process(master_bus_clk) begin
        if rising_edge(master_bus_clk) then
            if(master_bus_clk_rst = '1') then
                master_bus_miso <= (others => '0');
            elsif(master_bus_addr(1 downto 0) = "00") then
                master_bus_miso(16) <= rxcommadet;
                master_bus_miso(17) <= rxbyterealign;
                master_bus_miso(18) <= rxprbserr;
                master_bus_miso(19) <= rxbyteisaligned;
                master_bus_miso(20) <= rxprbslocked;
            end if;
        end if;
    end process bus_rd_proc;

    control_rxusrclk2_sync: xpm_cdc_array_single
        generic map (
            DEST_SYNC_FF => 4,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1,
            SRC_INPUT_REG => 0,
            WIDTH => 3 + 4
        )
        port map (
            src_clk => master_bus_clk,
            src_in(0) => rxcommadeten,
            src_in(1) => rxmcommaalignen,
            src_in(2) => rxpcommaalignen,
            src_in(6 downto 3) => rxprbssel,

            dest_clk => rx_clk_int,
            dest_out(0) => rxcommadeten_sync,
            dest_out(1) => rxmcommaalignen_sync,
            dest_out(2) => rxpcommaalignen_sync,
            dest_out(6 downto 3) => rxprbssel_sync
        );

    control_txusrclk2_sync: xpm_cdc_array_single
        generic map (
            DEST_SYNC_FF => 4,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1,
            SRC_INPUT_REG => 0,
            WIDTH => 4
        )
        port map (
            src_clk => master_bus_clk,
            src_in(3 downto 0) => txprbssel,

            dest_clk => tx_clk_int,
            dest_out(3 downto 0) => txprbssel_sync
        );

    -- Create latch reset signals based on what the bus commands
    gt_latch_reset <= master_bus_mosi(19 downto 16) when (master_bus_en = '1' 
                                        and master_bus_we = '1' 
                                        and master_bus_addr(1 downto 0) = "00") 
                        else (others => '0');

    latch_reset_sync: xpm_cdc_array_single
        generic map (
            DEST_SYNC_FF => 4,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1,
            SRC_INPUT_REG => 0,
            WIDTH => gt_latch_reset'length
        )
        port map (
            src_clk => master_bus_clk,
            src_in => gt_latch_reset,

            dest_clk => rx_clk_int,
            dest_out => gt_latch_reset_sync
        );

    -- Set or reset latches in the rxusrclk2 domain
    rxusrclk2_latches: process(rx_clk_int) begin
        if rising_edge(rx_clk_int) then
            rxcommadet_latch <= (rxcommadet_latch or rxcommadet_sync) and not gt_latch_reset_sync(0);
            rxbyterealign_latch <= (rxbyterealign_latch or rxbyterealign_sync) and not gt_latch_reset_sync(1);
            rxprbserr_latch <= (rxprbserr_latch or rxprbserr_sync) and not gt_latch_reset_sync(2);
        end if;
    end process rxusrclk2_latches;

    -- Transfer the latched status signals back into the bus domain
    latch_sync: xpm_cdc_array_single
        generic map (
            DEST_SYNC_FF => 4,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1,
            SRC_INPUT_REG => 0,
            WIDTH => gt_latch_reset'length
        )
        port map (
            src_clk => rx_clk_int,
            src_in(0) => rxcommadet_latch,
            src_in(1) => rxbyterealign_latch,
            src_in(2) => rxprbserr_latch,

            dest_clk => master_bus_clk,
            dest_out(0) => rxcommadet,
            dest_out(1) => rxbyterealign,
            dest_out(2) => rxprbserr
        );

    -- Transfer non-latched status signals from the gt back into the bus clock domain
    status_master_bus_clk_sync: xpm_cdc_array_single
        generic map (
            DEST_SYNC_FF => 4,
            INIT_SYNC_FF => 0,
            SIM_ASSERT_CHK => 1,
            SRC_INPUT_REG => 0,
            WIDTH => 2
        )
        port map (
            src_clk => rx_clk_int,
            src_in(0) => rxprbslocked_sync,
            src_in(1) => rxbyteisaligned_sync,

            dest_clk => master_bus_clk,
            dest_out(0) => rxprbslocked,
            dest_out(1) => rxbyteisaligned
        );

    gty_inst : gtwizard_ultrascale_0
        port map (
            -- Free-running clock for the reset helper block
            gtwiz_reset_clk_freerun_in   => clk,

            -- Resets clocking resources within the helper block
            -- Asynchronous
            gtwiz_userclk_tx_reset_in          => external_control(0),
            gtwiz_userclk_rx_reset_in          => external_control(1),

            -- Triggers for different pathways in the reset helper block
            -- Asynchronous
            gtwiz_reset_all_in                 => external_control(2),
            gtwiz_reset_tx_pll_and_datapath_in => external_control(3),
            gtwiz_reset_tx_datapath_in         => external_control(4),
            gtwiz_reset_rx_pll_and_datapath_in => external_control(5),
            gtwiz_reset_rx_datapath_in         => external_control(6),

            -- 8b10b and comma detection
            -- These connect directly to corresponding ports on the transceiver primitives
            -- Synchronous to TXUSRCLK2
            tx8b10ben_in => '1',
            
            -- These are all synchronous to RXUSRCLK2
            rx8b10ben_in       => '1',
            rxcommadeten_in    => rxcommadeten_sync,
            rxmcommaalignen_in => rxmcommaalignen_sync,
            rxpcommaalignen_in => rxpcommaalignen_sync,
            rxbyterealign_out  => rxbyterealign_sync,
            rxcommadet_out     => rxcommadet_sync,

            -- PRBS control and status
            -- These connect directly to corresponding ports on the transceiver primitives
            -- Synchronous to TXUSRCLK2
            txprbssel_in => txprbssel_sync,

            -- These are all synchronous to RXUSRCLK2
            rxprbscntreset_in => '0',
            rxprbssel_in => rxprbssel_sync,
            rxprbserr_out => rxprbserr_sync,
            rxprbslocked_out => rxprbslocked_sync,
            rxbyteisaligned_out => rxbyteisaligned_sync,
            

            -- Status signals
            -- Synchronous to gtwiz_userclk_tx_usrclk2_out
            gtwiz_userclk_tx_active_out   => external_status(0),
            -- Synchronous to gtwiz_userclk_rx_usrclk2_out
            gtwiz_userclk_rx_active_out   => external_status(1),
            -- Synchronous to gtwiz_reset_clk_freerun_in
            gtwiz_reset_rx_cdr_stable_out => external_status(2),
            -- Synchronous to TXUSRCLK2
            gtwiz_reset_tx_done_out       => external_status(3),
            -- Connects to corresponding port on transceiver primitive
            -- Asynchronous
            txpmaresetdone_out            => external_status(4),
            -- Synchronous to RXUSRCLK2
            gtwiz_reset_rx_done_out       => external_status(5),
            -- Connects to corresponding port on transceiver primitive
            -- Asynchronous
            rxpmaresetdone_out            => external_status(6),
            -- Connects to corresponding port on transceiver primitive
            -- Asynchronous
            rxprgdivresetdone_out         => external_status(7),
            -- Connects to corresponding port on transceiver primitive
            -- Asynchronous
            gtpowergood_out               => external_status(8),

            -- When the 8b10b decoder is enabled, the rxctrl signals behave as follows:
            --   If a valid K character is received, the corresponding bit of rxctrl0 is set.
            --   If positive comma detection is enabled and the positive comma is received, the corresponding bit of rxctrl2 is set. Same for negative comma.
            --   If a valid character with incorrect disparity is received, the corresponding bit of rxctrl1 is set.
            --   If an invalid character is received, the corresponding bit of rxctrl3 is set.
            -- These connect to the corresponding ports of the transceiver
            -- Synchronous to RXUSRCLK2
            rxctrl0_out(3 downto 0)       => rx_is_k_char,
            rxctrl1_out(3 downto 0)       => disparity_error,
            rxctrl2_out(3 downto 0)       => comma_detected,
            rxctrl3_out(3 downto 0)       => invalid_data,

            -- When 
            -- These connect to the corresponding ports of the transceiver
            -- Synchronous to RXUSRCLK2
            txctrl0_in => x"0000",
            txctrl1_in => x"0000",
            txctrl2_in(3 downto 0) => tx_is_k_char,
            txctrl2_in(7 downto 4) => x"0",

            -- Fabric-accessible clocks
            gtwiz_userclk_tx_srcclk_out  => open,
            gtwiz_userclk_tx_usrclk_out  => open,
            gtwiz_userclk_tx_usrclk2_out => tx_clk_int,
            gtwiz_userclk_rx_srcclk_out  => open,
            gtwiz_userclk_rx_usrclk_out  => open,
            gtwiz_userclk_rx_usrclk2_out => rx_clk_int,
            qpll0outclk_out              => open,
            qpll0outrefclk_out           => open,
            rxrecclkout_out              => open,

            -- Data interface
            gtwiz_userdata_tx_in  => gt_txdata,
            gtwiz_userdata_rx_out => gt_rxdata,
            
            -- Physical connections
            gtyrxn_in     => gt_rx_n,
            gtyrxp_in     => gt_rx_p,
            gtytxn_out    => gt_tx_n,
            gtytxp_out    => gt_tx_p,
            gtrefclk00_in => gt_refclk00
        );

        tx_clk <= tx_clk_int;
        rx_clk <= rx_clk_int;
    

end rtl;
